# Graph RAG Solution 配置文件

# 服务器配置
server:
  port: 8080

# Spring 配置
spring:
  application:
    name: graph-rag-api
  profiles:
    active: dev

# Graph RAG 配置
graph-rag:
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: password
    database: neo4j
  llm:
    provider: openai
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    base-url: https://deepseek-ivis-rag.openai.azure.com/
    model: gpt-3.5-turbo
    temperature: 0.7
    max-tokens: 1000
  embedding:
    provider: openai
    model: text-embedding-ada-002
    dimensions: 1536

# 日志配置
logging:
  level:
    com.graphrag: DEBUG
    org.neo4j: INFO
    dev.langchain4j: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Swagger 文档配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

